language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4

gemfile:
  - gemfiles/rails_3.x.gemfile
  - gemfiles/rails_4.1_with_sprockets_2.gemfile
  - gemfiles/rails_4.1_with_sprockets_3.gemfile
  - gemfiles/rails_4.2_with_sprockets_2.gemfile
  - gemfiles/rails_4.2_with_sprockets_3.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile

matrix:
  exclude:
    - rvm:     2.1
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm:     2.1
      gemfile: gemfiles/rails_5.1.gemfile

env:
  - RAKE_ENV=test RAILS_ENV=test

before_install:
  - npm install --global jade
  - npm install --global pug-cli
  - gem install bundler

install:
  - bundle install

script:
  - bundle exec rake test
